export const site = {
  title: '行走与观照',
  subtitle: '一个全球旅行者的城市、文明与生命笔记',
  author: 'Richard Xu',
  description: '一个全球旅行者的城市、文明与生命笔记。全文只活在这里。',
  lang: 'zh-Hans',
  navIndex: '目录',
  navThemes: '主题',
  navAbout: '关于',
  empty: '还没有写下第一座城市。',
  notFound: '没有这一页',
  draftLabel: '草稿',
  commentsHeading: '留言',
  skipToContent: '跳到正文',
  about: [
    '因为工作，我常年在城市之间移动。这是一份让我感恩的自由。每到一处，我抽出一天，去走，去看，去感受。',
    '写下来的不是攻略，也不是炫耀。是那一天真正看见的，以及当时的我带着什么走进这座城市。',
    '全文只活在这里。朋友圈、小红书、X 上的，都只是从这里摘出的一小截。',
  ],
  themes: [
    '自由与秩序',
    '权力与制度',
    '技术与人',
    '商业与社会',
    '信仰与超越',
    '移民与身份',
    '自然与文明',
    '创伤与重生',
    '教育与下一代',
    '内在自由',
  ],
  giscus: {
    repo: 'xufenglei2020/zaichang',
    repoId: 'R_kgDOT27uIw',
    category: 'General',
    categoryId: '',
    mapping: 'pathname',
    lang: 'zh-CN',
    theme: 'noborder_light',
  },
} as const;

export type SiteTheme = (typeof site.themes)[number];
